/* ══════════════════════════════════════════════════════
   download.js  —  PDF + DOCX export for all tools
   Depends on: docx (UMD), jsPDF, FileSaver
══════════════════════════════════════════════════════ */

/* ─────────────────────────────────────────────────────
   SHARED HELPERS
───────────────────────────────────────────────────── */
function splitBullets(raw) {
  return (raw || '').split('\n').map(b => b.trim()).filter(Boolean);
}

function today() {
  return new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

/* ── jsPDF text wrapper ── */
function pdfAddWrappedText(doc, text, x, y, maxW, lineH) {
  const lines = doc.splitTextToSize(text, maxW);
  doc.text(lines, x, y);
  return y + lines.length * lineH;
}

/* ── Generic plain-text → PDF ── */
function buildPlainPDF(title, sections) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const marginL = 60, marginR = 60, pageW = 612, maxW = pageW - marginL - marginR;
  const pageH = 792, footerH = 40;
  let y = 70;

  const addPage = () => { doc.addPage(); y = 60; };
  const checkY = (need) => { if (y + need > pageH - footerH) addPage(); };

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(17, 16, 9);
  doc.text(title, marginL, y); y += 32;

  // Subtitle line
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(125, 119, 105);
  doc.text(`Generated by CareerLaunch · ${today()}`, marginL, y); y += 24;

  // Rule
  const [ar, ag, ab] = (window.accentColor || {rgb:[200,151,58]}).rgb;
  doc.setDrawColor(ar, ag, ab);
  doc.setLineWidth(1.5);
  doc.line(marginL, y, pageW - marginR, y); y += 18;

  sections.forEach(sec => {
    if (!sec) return;
    checkY(40);

    // Section heading
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(ar, ag, ab);
    doc.text(sec.heading.toUpperCase(), marginL, y); y += 4;

    doc.setDrawColor(228, 222, 206);
    doc.setLineWidth(0.5);
    doc.line(marginL, y, pageW - marginR, y); y += 14;

    // Body lines
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(17, 16, 9);

    (sec.lines || []).forEach(line => {
      if (!line) return;
      if (line.startsWith('•')) {
        checkY(16);
        const wrapped = doc.splitTextToSize(line, maxW - 12);
        doc.text(wrapped, marginL + 12, y);
        y += wrapped.length * 14;
      } else if (line.startsWith('__bold__')) {
        checkY(14);
        doc.setFont('helvetica', 'bold');
        doc.text(line.replace('__bold__', ''), marginL, y);
        doc.setFont('helvetica', 'normal');
        y += 14;
      } else {
        checkY(14);
        const wrapped = doc.splitTextToSize(line, maxW);
        doc.text(wrapped, marginL, y);
        y += wrapped.length * 14;
      }
    });
    y += 16;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(125, 119, 105);
    doc.text(`CareerLaunch · Page ${i} of ${pageCount}`, marginL, pageH - 20);
  }

  return doc;
}

/* ── Generic plain-text → DOCX ── */
function buildPlainDOCX(title, sections) {
  const { Document, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, Packer } = docx;

  const children = [];

  // Title
  children.push(new Paragraph({
    children: [new TextRun({ text: title, bold: true, size: 40, color: '111009' })],
    spacing: { after: 100 },
  }));

  // Subtitle
  children.push(new Paragraph({
    children: [new TextRun({ text: `Generated by CareerLaunch · ${today()}`, size: 18, color: '7d7769' })],
    spacing: { after: 200 },
  }));

  sections.forEach(sec => {
    if (!sec) return;

    // Section heading
    children.push(new Paragraph({
      children: [new TextRun({ text: sec.heading.toUpperCase(), bold: true, size: 20, color: (window.accentColor || {hex:'#c8913a'}).hex.replace('#','') })],
      spacing: { before: 240, after: 60 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: 'e4dece' } },
    }));

    (sec.lines || []).forEach(line => {
      if (!line) return;
      if (line.startsWith('•')) {
        children.push(new Paragraph({
          children: [new TextRun({ text: line, size: 20 })],
          indent: { left: 240 },
          spacing: { after: 60 },
        }));
      } else if (line.startsWith('__bold__')) {
        children.push(new Paragraph({
          children: [new TextRun({ text: line.replace('__bold__', ''), bold: true, size: 20 })],
          spacing: { after: 60 },
        }));
      } else {
        children.push(new Paragraph({
          children: [new TextRun({ text: line, size: 20 })],
          spacing: { after: 60 },
        }));
      }
    });
  });

  return new Document({ sections: [{ children }] });
}

/* ─────────────────────────────────────────────────────
   RESUME
───────────────────────────────────────────────────── */
function downloadPDF() {
  const s = resumeState;
  const name = s.contact.name || 'Resume';
  const allSkills = [...s.hardSkills, ...s.softSkills];
  const sections = [];

  if (s.summary) sections.push({ heading: 'Professional Summary', lines: [s.summary] });

  const expLines = [];
  s.experiences.filter(e => e.title).forEach(e => {
    expLines.push(`__bold__${e.title}${e.org ? ' — ' + e.org : ''}${e.dates ? '  |  ' + e.dates : ''}`);
    splitBullets(e.bullets).forEach(b => expLines.push('• ' + b));
    expLines.push('');
  });
  if (expLines.length) sections.push({ heading: 'Experience', lines: expLines });

  if (allSkills.length) sections.push({ heading: 'Skills', lines: [allSkills.join('  ·  ')] });

  const doc = buildPlainPDF(name, sections);
  // Contact block at top — inject before sections
  const { jsPDF } = window.jspdf;
  doc.save(`${name.replace(/\s+/g, '_')}_Resume.pdf`);
}

function downloadDOCX() {
  const s = resumeState;
  const name = s.contact.name || 'Resume';
  const allSkills = [...s.hardSkills, ...s.softSkills];
  const sections = [];

  const contactParts = [s.contact.email, s.contact.phone, s.contact.location].filter(Boolean);
  if (contactParts.length) sections.push({ heading: 'Contact', lines: [contactParts.join('  ·  ')] });
  if (s.summary) sections.push({ heading: 'Professional Summary', lines: [s.summary] });

  const expLines = [];
  s.experiences.filter(e => e.title).forEach(e => {
    expLines.push(`__bold__${e.title}${e.org ? ' — ' + e.org : ''}${e.dates ? '  |  ' + e.dates : ''}`);
    splitBullets(e.bullets).forEach(b => expLines.push('• ' + b));
    expLines.push('');
  });
  if (expLines.length) sections.push({ heading: 'Experience', lines: expLines });
  if (allSkills.length) sections.push({ heading: 'Skills', lines: [allSkills.join('  ·  ')] });

  const document = buildPlainDOCX(name, sections);
  docx.Packer.toBlob(document).then(blob => {
    saveAs(blob, `${name.replace(/\s+/g, '_')}_Resume.docx`);
  });
}

/* ─────────────────────────────────────────────────────
   LINKEDIN
───────────────────────────────────────────────────── */
function buildLinkedinSections() {
  const s = linkedinState;
  const fieldLabel = FIELDS.find(f => f.id === s.field)?.label || s.field;
  const sections = [];
  const headline = [s.who, s.skill, s.goal ? 'Open to ' + s.goal : ''].filter(Boolean).join(' | ');
  if (headline) sections.push({ heading: 'Headline', lines: [headline] });
  if (s.about) sections.push({ heading: 'About Section', lines: s.about.split('\n') });
  if (fieldLabel) sections.push({ heading: 'Field', lines: [fieldLabel] });
  sections.push({ heading: 'Next Steps', lines: [
    '• Go to linkedin.com/profile/edit to apply these to your real profile.',
    '• Upload a professional headshot.',
    '• Connect with teachers, past employers, and industry contacts.',
    '• Send a personal note with every connection request.',
  ]});
  return sections;
}

function downloadLinkedinPDF() {
  const doc = buildPlainPDF('LinkedIn Profile Builder', buildLinkedinSections());
  doc.save('LinkedIn_Profile.pdf');
}
function downloadLinkedinDOCX() {
  const document = buildPlainDOCX('LinkedIn Profile Builder', buildLinkedinSections());
  docx.Packer.toBlob(document).then(blob => saveAs(blob, 'LinkedIn_Profile.docx'));
}

/* ─────────────────────────────────────────────────────
   PORTFOLIO
───────────────────────────────────────────────────── */
function buildPortfolioSections() {
  const s = portfolioState;
  const fieldLabel = FIELDS.find(f => f.id === s.field)?.label || s.field;
  const sections = [];
  if (fieldLabel) sections.push({ heading: 'Field', lines: [fieldLabel] });
  if (s.format) sections.push({ heading: 'Format', lines: [s.format] });
  s.projects.forEach((p, i) => {
    const lines = [];
    if (p.goal)     lines.push(`__bold__Goal:`, p.goal, '');
    if (p.problem)  lines.push(`__bold__Problem:`, p.problem, '');
    if (p.created)  lines.push(`__bold__What I Created:`, p.created, '');
    if (p.tools)    lines.push(`__bold__Tools Used:`, p.tools, '');
    if (p.outcome)  lines.push(`__bold__Outcome:`, p.outcome, '');
    if (p.learned)  lines.push(`__bold__What I Learned:`, p.learned, '');
    if (lines.length) sections.push({ heading: `Project ${i + 1}`, lines });
  });
  return sections;
}

function downloadPortfolioPDF() {
  const doc = buildPlainPDF('Portfolio Builder', buildPortfolioSections());
  doc.save('Portfolio.pdf');
}
function downloadPortfolioDOCX() {
  const document = buildPlainDOCX('Portfolio Builder', buildPortfolioSections());
  docx.Packer.toBlob(document).then(blob => saveAs(blob, 'Portfolio.docx'));
}

/* ─────────────────────────────────────────────────────
   COVER LETTER
───────────────────────────────────────────────────── */
function buildCoverLetterSections() {
  const s = clState;
  const sections = [];
  if (s.company || s.position) sections.push({
    heading: 'Position',
    lines: [`${s.position || '[Position]'} at ${s.company || '[Company]'}`],
  });
  if (s.opening) sections.push({ heading: 'Opening Paragraph', lines: s.opening.split('\n') });
  if (s.body1)   sections.push({ heading: 'Body — Experience', lines: s.body1.split('\n') });
  if (s.body2)   sections.push({ heading: 'Body — Strengths', lines: s.body2.split('\n') });
  if (s.closing) sections.push({ heading: 'Closing Paragraph', lines: s.closing.split('\n') });
  return sections;
}

function downloadCoverLetterPDF() {
  const title = `Cover Letter${clState.company ? ' — ' + clState.company : ''}`;
  const doc = buildPlainPDF(title, buildCoverLetterSections());
  doc.save('Cover_Letter.pdf');
}
function downloadCoverLetterDOCX() {
  const title = `Cover Letter${clState.company ? ' — ' + clState.company : ''}`;
  const document = buildPlainDOCX(title, buildCoverLetterSections());
  docx.Packer.toBlob(document).then(blob => saveAs(blob, 'Cover_Letter.docx'));
}

/* ─────────────────────────────────────────────────────
   INTERVIEW PREP
───────────────────────────────────────────────────── */
function buildInterviewSections() {
  const s = interviewState;
  const fieldLabel = FIELDS.find(f => f.id === s.field)?.label || s.field;
  const commonQs = [
    'Tell me about yourself.',
    'Why should we hire you?',
    'What is your biggest strength?',
    'What is a weakness?',
    'Describe a time you solved a problem.',
  ];
  const sections = [];
  if (fieldLabel) sections.push({ heading: 'Field', lines: [fieldLabel] });

  const commonLines = [];
  commonQs.forEach((q, i) => {
    commonLines.push(`__bold__${q}`);
    commonLines.push(s.answers['q' + i] || '(No answer written yet)');
    commonLines.push('');
  });
  sections.push({ heading: 'Common Questions', lines: commonLines });

  const fieldQs = INTERVIEW_QUESTIONS[s.field] || INTERVIEW_QUESTIONS.general;
  const fieldLines = [];
  fieldQs.forEach((q, i) => {
    fieldLines.push(`__bold__${q}`);
    fieldLines.push(s.answers['fq' + i] || '(No answer written yet)');
    fieldLines.push('');
  });
  sections.push({ heading: `Field-Specific Questions — ${fieldLabel}`, lines: fieldLines });

  sections.push({ heading: 'Reminders', lines: [
    '• Send a thank-you email within 24 hours of your interview.',
    '• Practice answers out loud — not just in your head.',
    '• Arrive 10–15 minutes early (or log in early for virtual).',
    '• Bring 2 printed copies of your resume.',
  ]});
  return sections;
}

function downloadInterviewPDF() {
  const doc = buildPlainPDF('Interview Prep Notes', buildInterviewSections());
  doc.save('Interview_Prep.pdf');
}
function downloadInterviewDOCX() {
  const document = buildPlainDOCX('Interview Prep Notes', buildInterviewSections());
  docx.Packer.toBlob(document).then(blob => saveAs(blob, 'Interview_Prep.docx'));
}

/* ─────────────────────────────────────────────────────
   COLLEGE APPLICATIONS
───────────────────────────────────────────────────── */
function buildCollegeSections() {
  const s = collegeState;
  const sections = [];
  if (s.essayDraft) sections.push({ heading: 'Personal Statement Draft', lines: s.essayDraft.split('\n') });

  const actLines = s.activities.filter(Boolean).map((a, i) => `• Activity ${i + 1}: ${a}`);
  if (actLines.length) sections.push({ heading: 'Activities List', lines: actLines });

  if (s.thankYouNote) sections.push({ heading: 'Thank You Note Template', lines: s.thankYouNote.split('\n') });

  sections.push({ heading: 'Pre-Submission Checklist', lines: [
    '• Personal statement — revised & proofread (read aloud, 2+ people reviewed)',
    '• Activities list complete — ordered by importance, hours/week filled in',
    '• Supplemental essays customized per school — no generic "Why us?" answers',
    '• Official transcripts requested from registrar',
    '• SAT/ACT scores sent directly from College Board or ACT',
    '• Recommendation writers have resume, draft, and deadlines confirmed',
    '• FAFSA submitted (as early as possible after Oct 1)',
    '• Counselor has reviewed your school list',
  ]});
  return sections;
}

function downloadCollegePDF() {
  const doc = buildPlainPDF('College Application Toolkit', buildCollegeSections());
  doc.save('College_Applications.pdf');
}
function downloadCollegeDOCX() {
  const document = buildPlainDOCX('College Application Toolkit', buildCollegeSections());
  docx.Packer.toBlob(document).then(blob => saveAs(blob, 'College_Applications.docx'));
}

/* ─────────────────────────────────────────────────────
   STERLING SCHOLAR
───────────────────────────────────────────────────── */
function buildSterlingSections() {
  const s = sterlingState;
  const cat = (typeof SS_CATEGORIES !== 'undefined')
    ? SS_CATEGORIES.find(x => x.id === s.ssCategory)
    : null;
  const sections = [];

  if (cat) sections.push({ heading: 'Category', lines: [`${cat.name}`, cat.desc, '', `Key evidence: ${cat.evidence}`, cat.special || ''].filter(l => l !== undefined) });

  if (s.essayDraft) sections.push({ heading: 'Narrative Essay Draft', lines: s.essayDraft.split('\n') });

  if (s.serviceLog) sections.push({ heading: 'Community Service Log', lines: s.serviceLog.split('\n') });

  if (s.thankYouNote) sections.push({ heading: 'Thank You Note Template', lines: s.thankYouNote.split('\n') });

  sections.push({ heading: 'Portfolio Binder Checklist', lines: [
    '• Nominated by a teacher in your category',
    '• Binder organized with tabbed dividers',
    '• Personal statement written and polished (1–2 pages)',
    '• Academic record included (transcript + GPA)',
    '• Résumé current and field-specific',
    '• Evidence of excellence (awards, certifications, competition results)',
    '• Community service log complete (dates, org, hours, role, supervisor)',
    '• Letters of recommendation (2+) secured',
    '• Work samples included',
  ]});

  sections.push({ heading: 'Interview Day Checklist', lines: [
    '• Mock interview done at least twice',
    '• Know your portfolio cold — ready to speak to any page',
    '• Business professional outfit ready',
    '• Prepared questions to ask judges',
    '• All exhibits carried in one trip (no carts allowed)',
    '• Thank-you notes written and ready to send within 24 hours',
  ]});

  return sections;
}

function downloadSterlingPDF() {
  const doc = buildPlainPDF('Sterling Scholar Portfolio', buildSterlingSections());
  doc.save('Sterling_Scholar.pdf');
}
function downloadSterlingDOCX() {
  const document = buildPlainDOCX('Sterling Scholar Portfolio', buildSterlingSections());
  docx.Packer.toBlob(document).then(blob => saveAs(blob, 'Sterling_Scholar.docx'));
}
